# Generated by Django 3.2.5 on 2021-07-16 12:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0004_alter_realtors_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('town', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('sale_type', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent'), ('For Lease', 'For Lease')], default='For Sale', max_length=65)),
                ('home_type', models.CharField(choices=[('House', 'House'), ('Land', 'Land'), ('Town House', 'Town House'), ('Condo', 'Condo'), ('Pent House', 'Pent House')], default='House', max_length=65)),
                ('sqft', models.IntegerField(default=0)),
                ('main_photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtors')),
            ],
            options={
                'verbose_name_plural': 'Listings',
            },
        ),
    ]
