# Generated by Django 3.2.5 on 2021-07-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
