# Generated by Django 3.2.5 on 2021-07-16 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Realtors',
        ),
    ]
