# Generated by Django 3.2.5 on 2021-07-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_realtors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtors',
            options={'verbose_name_plural': 'Realtors'},
        ),
    ]
